[tool.poetry]
name = "mcp-mem0"
version = "0.1.0"
description = "MCP Memory Management System"
authors = ["tradesdontlie"]

[tool.poetry.dependencies]
python = "^3.8"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"